# Generated by Django 4.2.7 on 2026-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productweight'),
        ('cart', '0002_checkout_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'product_weight')},
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
